buildscript {
    //ext.kotlin_version = '1.8.0'
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.0.2' // Use a versFo correta do Android Gradle Plugin
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
