# Exemplo de gradle.properties
#memória ram que será gasta no build, coloquei apenas 512 por causa do pc😅
org.gradle.jvmargs=-Xmx512m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true

#definições de proxy, eu uso vpn, deixa comentado mesmo
#systemProp.http.proxyHost=192.168.23.221
#systemProp.http.proxyPort=8118
#systemProp.http.proxyUser=
#systemProp.http.proxyPassword=

#systemProp.https.proxyHost=192.168.23.221
#systemProp.https.proxyPort=8118
#systemProp.https.proxyUser=
#systemProp.https.proxyPassword=
